services:
  postgres:
    image: postgres:18-alpine
    container_name: macaw_postgres
    restart: unless-stopped

    ports:
      - "5450:5432"

    environment:
      POSTGRES_USER: macaw
      POSTGRES_PASSWORD: macaw123
      POSTGRES_DB: macaw_db
     

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U macaw"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: