const ERROR_CODES = {
  INTERNAL: "INTERNAL_ERROR",
  VALIDATION: "VALIDATION_ERROR",
  NOT_FOUND: "RESOURCE_NOT_FOUND",
  RATE_LIMITED: "RATE_LIMITED",
  CORS_ORIGIN_NOT_ALLOWED: "CORS_ORIGIN_NOT_ALLOWED",

  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_TOKEN_MISSING: "AUTH_TOKEN_MISSING",
  AUTH_TOKEN_INVALID: "AUTH_TOKEN_INVALID",
  AUTH_ACCOUNT_DISABLED: "AUTH_ACCOUNT_DISABLED",
  AUTH_EMAIL_TAKEN: "AUTH_EMAIL_TAKEN",
  AUTH_ROLE_NOT_ALLOWED: "AUTH_ROLE_NOT_ALLOWED",
  AUTH_FORBIDDEN: "AUTH_FORBIDDEN",

  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_NOT_STUDENT: "USER_NOT_STUDENT",
  USER_CANNOT_DISABLE_ADMIN: "USER_CANNOT_DISABLE_ADMIN",

  TOKEN_INVALID: "TOKEN_INVALID",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  PASSWORD_INCORRECT: "PASSWORD_INCORRECT",
  PASSWORD_SAME_AS_CURRENT: "PASSWORD_SAME_AS_CURRENT",
  EMAIL_ALREADY_VERIFIED: "EMAIL_ALREADY_VERIFIED",

  UPLOAD_NOT_CONFIGURED: "UPLOAD_NOT_CONFIGURED",
  UPLOAD_FILE_REQUIRED: "UPLOAD_FILE_REQUIRED",
  UPLOAD_FILE_TOO_LARGE: "UPLOAD_FILE_TOO_LARGE",
  UPLOAD_TYPE_NOT_ALLOWED: "UPLOAD_TYPE_NOT_ALLOWED",
  UPLOAD_FAILED: "UPLOAD_FAILED",

  NOTIFICATION_NOT_FOUND: "NOTIFICATION_NOT_FOUND",

  TUTOR_ALREADY_VERIFIED: "TUTOR_ALREADY_VERIFIED",
  TUTOR_NOT_IN_INSTITUTION: "TUTOR_NOT_IN_INSTITUTION",
  TUTOR_NOT_VERIFIED_IN_INSTITUTION: "TUTOR_NOT_VERIFIED_IN_INSTITUTION",
  TUTOR_MEMBERSHIP_EXISTS: "TUTOR_MEMBERSHIP_EXISTS",
  TUTOR_MEMBERSHIP_NOT_FOUND: "TUTOR_MEMBERSHIP_NOT_FOUND",
  TUTOR_MEMBERSHIP_NOT_PENDING: "TUTOR_MEMBERSHIP_NOT_PENDING",
  TUTOR_ALREADY_HAS_ACCOUNT: "TUTOR_ALREADY_HAS_ACCOUNT",

  INSTITUTION_NOT_FOUND: "INSTITUTION_NOT_FOUND",
  INSTITUTION_REQUIRED: "INSTITUTION_REQUIRED",
  INSTITUTION_MISMATCH: "INSTITUTION_MISMATCH",
  INSTITUTION_INSUFFICIENT_BALANCE: "INSTITUTION_INSUFFICIENT_BALANCE",
  INSTITUTION_SUSPENDED: "INSTITUTION_SUSPENDED",
  INSTITUTION_DOMAIN_TAKEN: "INSTITUTION_DOMAIN_TAKEN",
  INSTITUTION_NAME_REQUIRED: "INSTITUTION_NAME_REQUIRED",
  INSTITUTION_CURRENCY_LOCKED: "INSTITUTION_CURRENCY_LOCKED",
  INSTITUTION_HAS_USERS: "INSTITUTION_HAS_USERS",
  INSTITUTION_HAS_STRUCTURE: "INSTITUTION_HAS_STRUCTURE",
  INSTITUTION_HAS_LEDGER: "INSTITUTION_HAS_LEDGER",

  DOMAIN_NOT_FOUND: "DOMAIN_NOT_FOUND",
  DOMAIN_ALREADY_VERIFIED: "DOMAIN_ALREADY_VERIFIED",
  DOMAIN_VERIFICATION_NOT_STARTED: "DOMAIN_VERIFICATION_NOT_STARTED",
  DOMAIN_VERIFICATION_FAILED: "DOMAIN_VERIFICATION_FAILED",
  DOMAIN_IS_PRIMARY: "DOMAIN_IS_PRIMARY",

  INVITATION_NOT_FOUND: "INVITATION_NOT_FOUND",
  INVITATION_NOT_PENDING: "INVITATION_NOT_PENDING",
  INVITATION_EXPIRED: "INVITATION_EXPIRED",
  INVITATION_ALREADY_SENT: "INVITATION_ALREADY_SENT",
  INVITATION_ROLE_NOT_ALLOWED: "INVITATION_ROLE_NOT_ALLOWED",

  TEMPLATE_NOT_FOUND: "TEMPLATE_NOT_FOUND",

  IMPORT_EMPTY: "IMPORT_EMPTY",
  IMPORT_TOO_MANY_ROWS: "IMPORT_TOO_MANY_ROWS",
  IMPORT_MISSING_COLUMNS: "IMPORT_MISSING_COLUMNS",
  IMPORT_MALFORMED: "IMPORT_MALFORMED",

  EXCHANGE_RATE_INVALID: "EXCHANGE_RATE_INVALID",

  PLAN_CODE_TAKEN: "PLAN_CODE_TAKEN",
  PLAN_IN_USE: "PLAN_IN_USE",
  PLAN_TOO_SMALL: "PLAN_TOO_SMALL",

  ENDPOINT_GONE: "ENDPOINT_GONE",

  CROSS_INSTITUTION_NOT_ALLOWED: "CROSS_INSTITUTION_NOT_ALLOWED",
  CROSS_CURRENCY_NOT_ALLOWED: "CROSS_CURRENCY_NOT_ALLOWED",

  CURRENCY_NOT_FOUND: "CURRENCY_NOT_FOUND",
  CURRENCY_NOT_ACTIVE: "CURRENCY_NOT_ACTIVE",

  PLAN_NOT_FOUND: "PLAN_NOT_FOUND",
  PLAN_STUDENT_LIMIT_REACHED: "PLAN_STUDENT_LIMIT_REACHED",
  SUBSCRIPTION_NOT_FOUND: "SUBSCRIPTION_NOT_FOUND",

  ACADEMIC_UNIT_NOT_FOUND: "ACADEMIC_UNIT_NOT_FOUND",
  ACADEMIC_UNIT_REQUIRED: "ACADEMIC_UNIT_REQUIRED",
  ACADEMIC_UNIT_CODE_TAKEN: "ACADEMIC_UNIT_CODE_TAKEN",
  GRADE_LEVEL_NOT_FOUND: "GRADE_LEVEL_NOT_FOUND",
  GRADE_LEVEL_CODE_TAKEN: "GRADE_LEVEL_CODE_TAKEN",
  GRADE_LEVEL_HAS_STUDENTS: "GRADE_LEVEL_HAS_STUDENTS",

  SUBJECT_NOT_FOUND: "SUBJECT_NOT_FOUND",
  SUBJECT_CODE_TAKEN: "SUBJECT_CODE_TAKEN",
  SUBJECT_GENERAL_RESTRICTED: "SUBJECT_GENERAL_RESTRICTED",
  SUBJECT_HAS_TUTORS: "SUBJECT_HAS_TUTORS",
  SUBJECT_HAS_SESSIONS: "SUBJECT_HAS_SESSIONS",

  TUTOR_NOT_FOUND: "TUTOR_NOT_FOUND",
  TUTOR_PROFILE_NOT_FOUND: "TUTOR_PROFILE_NOT_FOUND",
  TUTOR_SUBJECT_ALREADY_ADDED: "TUTOR_SUBJECT_ALREADY_ADDED",
  TUTOR_DOES_NOT_TEACH_SUBJECT: "TUTOR_DOES_NOT_TEACH_SUBJECT",
  TUTOR_UNAVAILABLE_DAY: "TUTOR_UNAVAILABLE_DAY",
  TUTOR_SLOT_OUTSIDE_AVAILABILITY: "TUTOR_SLOT_OUTSIDE_AVAILABILITY",

  SESSION_NOT_FOUND: "SESSION_NOT_FOUND",
  SESSION_ACCESS_DENIED: "SESSION_ACCESS_DENIED",
  SESSION_INVALID_TIME_RANGE: "SESSION_INVALID_TIME_RANGE",
  SESSION_IN_THE_PAST: "SESSION_IN_THE_PAST",
  SESSION_TUTOR_SLOT_TAKEN: "SESSION_TUTOR_SLOT_TAKEN",
  SESSION_STUDENT_SLOT_TAKEN: "SESSION_STUDENT_SLOT_TAKEN",
  SESSION_NOT_PENDING: "SESSION_NOT_PENDING",
  SESSION_NOT_CONFIRMED: "SESSION_NOT_CONFIRMED",
  SESSION_NOT_PENDING_CONFIRMATION: "SESSION_NOT_PENDING_CONFIRMATION",
  SESSION_NOT_CANCELLABLE: "SESSION_NOT_CANCELLABLE",
  SESSION_NOT_DISPUTED: "SESSION_NOT_DISPUTED",
  SESSION_STATE_CHANGED: "SESSION_STATE_CHANGED",
  SESSION_INVALID_RESOLUTION: "SESSION_INVALID_RESOLUTION",

  WALLET_NOT_FOUND: "WALLET_NOT_FOUND",
  WALLET_INSUFFICIENT_BALANCE: "WALLET_INSUFFICIENT_BALANCE",
  WALLET_INVALID_AMOUNT: "WALLET_INVALID_AMOUNT",
  WALLET_SELF_TOPUP_DISABLED: "WALLET_SELF_TOPUP_DISABLED",
  WALLET_CURRENCY_MISMATCH: "WALLET_CURRENCY_MISMATCH",

  LEDGER_UNBALANCED: "LEDGER_UNBALANCED",
  LEDGER_INVALID_AMOUNT: "LEDGER_INVALID_AMOUNT",
  LEDGER_CURRENCY_MISMATCH: "LEDGER_CURRENCY_MISMATCH",
  LEDGER_DUPLICATE_ENTRY: "LEDGER_DUPLICATE_ENTRY",

  WITHDRAWALS_DISABLED: "WITHDRAWALS_DISABLED",

  WITHDRAWAL_NOT_FOUND: "WITHDRAWAL_NOT_FOUND",
  WITHDRAWAL_ALREADY_PENDING: "WITHDRAWAL_ALREADY_PENDING",
  WITHDRAWAL_ALREADY_PROCESSED: "WITHDRAWAL_ALREADY_PROCESSED",
  WITHDRAWAL_PAYPAL_EMAIL_REQUIRED: "WITHDRAWAL_PAYPAL_EMAIL_REQUIRED",

  PAYMENT_INVALID_AMOUNT: "PAYMENT_INVALID_AMOUNT",
  PAYMENT_ORDER_REQUIRED: "PAYMENT_ORDER_REQUIRED",
  PAYMENT_ORDER_NOT_FOUND: "PAYMENT_ORDER_NOT_FOUND",
  PAYMENT_ORDER_NOT_OWNED: "PAYMENT_ORDER_NOT_OWNED",
  PAYMENT_NOT_COMPLETED: "PAYMENT_NOT_COMPLETED",
  PAYMENT_ALREADY_PROCESSED: "PAYMENT_ALREADY_PROCESSED",
  PAYMENT_PROVIDER_ERROR: "PAYMENT_PROVIDER_ERROR",
  PAYMENT_CURRENCY_NOT_SUPPORTED: "PAYMENT_CURRENCY_NOT_SUPPORTED",
  PAYMENT_CURRENCY_MISMATCH: "PAYMENT_CURRENCY_MISMATCH",
  PAYMENT_AMOUNT_MISMATCH: "PAYMENT_AMOUNT_MISMATCH",

  REVIEW_NOT_FOUND: "REVIEW_NOT_FOUND",
  REVIEW_ALREADY_EXISTS: "REVIEW_ALREADY_EXISTS",
  REVIEW_SESSION_NOT_COMPLETED: "REVIEW_SESSION_NOT_COMPLETED",
  REVIEW_INVALID_RATING: "REVIEW_INVALID_RATING",

  AI_INVALID_RESPONSE: "AI_INVALID_RESPONSE",
  AI_NOT_CONFIGURED: "AI_NOT_CONFIGURED",

  PLATFORM_WALLET_NOT_FOUND: "PLATFORM_WALLET_NOT_FOUND",
};

module.exports = ERROR_CODES;
