const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();

const GENERAL_SUBJECTS = [
  { name: "Español", code: "ES101", termNumber: 1, credits: 3, isGeneral: true },
  {
    name: "Biología I",
    code: "BG101",
    termNumber: 1,
    credits: 4,
    isGeneral: true,
  },
  {
    name: "Matematicas",
    code: "MT101",
    termNumber: 1,
    credits: 4,
    isGeneral: true,
  },
  {
    name: "Sociología",
    code: "SC101",
    termNumber: 1,
    credits: 3,
    isGeneral: true,
  },
  { name: "Filosofía", code: "FI101", termNumber: 1, credits: 3, isGeneral: true },
  { name: "Dibujo I", code: "DB201", termNumber: 1, credits: 3, isGeneral: true },
  { name: "Química I", code: "QM101", termNumber: 1, credits: 5, isGeneral: true },
  {
    name: "Química Orgánica",
    code: "QM206",
    termNumber: 2,
    credits: 5,
    isGeneral: true,
  },
  {
    name: "Expresión Oral y Escrita",
    code: "ES201",
    termNumber: 2,
    credits: 3,
    isGeneral: true,
  },
  {
    name: "Dibujo Técnico",
    code: "DB301",
    termNumber: 2,
    credits: 3,
    isGeneral: true,
  },
  {
    name: "Pre Calculo",
    code: "MT201",
    termNumber: 2,
    credits: 4,
    isGeneral: true,
  },
  {
    name: "Historia de Honduras",
    code: "HS101",
    termNumber: 2,
    credits: 3,
    isGeneral: true,
  },
  {
    name: "El Hombre Frente a la Vida",
    code: "CR201",
    termNumber: 2,
    credits: 3,
    isGeneral: true,
  },
  {
    name: "Estadística I",
    code: "MT202",
    termNumber: 2,
    credits: 4,
    isGeneral: true,
  },
  { name: "Física I", code: "FS201", termNumber: 2, credits: 3, isGeneral: true },
  { name: "Física II", code: "FS301", termNumber: 2, credits: 3, isGeneral: true },
  {
    name: "Administración I",
    code: "AD101",
    termNumber: 2,
    credits: 3,
    isGeneral: true,
  },
  {
    name: "Matemáticas Financiera",
    code: "MT204",
    termNumber: 2,
    credits: 4,
    isGeneral: true,
  },
  {
    name: "Informática I",
    code: "IF101",
    termNumber: 2,
    credits: 3,
    isGeneral: true,
  },
  { name: "Nutrición", code: "MD403", termNumber: 2, credits: 3, isGeneral: true },
  {
    name: "Diseño Grafico",
    code: "IF394",
    termNumber: 2,
    credits: 3,
    isGeneral: true,
  },
  { name: "Ecología", code: "BG205", termNumber: 2, credits: 3, isGeneral: true },
  {
    name: "Excel Avanzado para Ingenierias",
    code: "IF393",
    termNumber: 2,
    credits: 3,
    isGeneral: true,
  },
  {
    name: "Estadística II",
    code: "MT302",
    termNumber: 3,
    credits: 4,
    isGeneral: true,
  },
  { name: "Estática", code: "IG302", termNumber: 3, credits: 3, isGeneral: true },
  {
    name: "Topografía",
    code: "IG301",
    termNumber: 3,
    credits: 3,
    isGeneral: true,
  },
  {
    name: "Bioestadística",
    code: "MD202",
    termNumber: 3,
    credits: 3,
    isGeneral: true,
  },
  {
    name: "Bioquímica",
    code: "QM301",
    termNumber: 3,
    credits: 6,
    isGeneral: true,
  },
  { name: "Calculo I", code: "MT303", termNumber: 3, credits: 4, isGeneral: true },
  {
    name: "Administración II",
    code: "AD201",
    termNumber: 3,
    credits: 3,
    isGeneral: true,
  },
  {
    name: "Métodos y Técnicas de Investigación",
    code: "AD302",
    termNumber: 3,
    credits: 3,
    isGeneral: true,
  },
  {
    name: "Contabilidad I",
    code: "CT201",
    termNumber: 3,
    credits: 3,
    isGeneral: true,
  },
  {
    name: "Ética Profesional",
    code: "FI501",
    termNumber: 3,
    credits: 3,
    isGeneral: true,
  },
  {
    name: "Ética Médica",
    code: "CR203",
    termNumber: 3,
    credits: 3,
    isGeneral: true,
  },
  {
    name: "Gestión de la Calidad Total",
    code: "AD104",
    termNumber: 3,
    credits: 3,
    isGeneral: true,
  },
  {
    name: "Informática II",
    code: "IF201",
    termNumber: 3,
    credits: 3,
    isGeneral: true,
  },
  {
    name: "Ecuaciones Diferenciales",
    code: "MT501",
    termNumber: 3,
    credits: 3,
    isGeneral: true,
  },
  {
    name: "Algebra Lineal",
    code: "MT301",
    termNumber: 3,
    credits: 3,
    isGeneral: true,
  },
  {
    name: "Ciencia y Tecnología",
    code: "FI102",
    termNumber: 3,
    credits: 3,
    isGeneral: true,
  },
  {
    name: "Calculo II",
    code: "MT401",
    termNumber: 4,
    credits: 4,
    isGeneral: true,
  },
  {
    name: "Contabilidad II",
    code: "CT301",
    termNumber: 4,
    credits: 3,
    isGeneral: true,
  },
  {
    name: "Control Estadístico de la Calidad",
    code: "MT304",
    termNumber: 4,
    credits: 3,
    isGeneral: true,
  },
  {
    name: "Doctrina Social de la Iglesia",
    code: "CR501",
    termNumber: 4,
    credits: 3,
    isGeneral: true,
  },
  {
    name: "Mercadotecnia I",
    code: "MC201",
    termNumber: 4,
    credits: 3,
    isGeneral: true,
  },
  {
    name: "Contabilidad Administrativa I",
    code: "CT403",
    termNumber: 4,
    credits: 3,
    isGeneral: true,
  },
  {
    name: "Embriología",
    code: "BG206",
    termNumber: 4,
    credits: 6,
    isGeneral: true,
  },
  {
    name: "Psicología Médica",
    code: "PS104",
    termNumber: 4,
    credits: 3,
    isGeneral: true,
  },
  {
    name: "Planeación y Diseño de un Modelo de Calidad",
    code: "AD402",
    termNumber: 5,
    credits: 3,
    isGeneral: true,
  },
  {
    name: "Análisis Estructural I",
    code: "IG404",
    termNumber: 5,
    credits: 3,
    isGeneral: true,
  },
  {
    name: "Legislación Empresarial",
    code: "LG201",
    termNumber: 5,
    credits: 3,
    isGeneral: true,
  },
  {
    name: "Administración de Recursos Humanos",
    code: "AD202",
    termNumber: 5,
    credits: 3,
    isGeneral: true,
  },
  {
    name: "Investigación de Mercados I",
    code: "MC301",
    termNumber: 5,
    credits: 3,
    isGeneral: true,
  },
  {
    name: "Administración Financiera I",
    code: "FZ301",
    termNumber: 5,
    credits: 3,
    isGeneral: true,
  },
  {
    name: "Histología",
    code: "MD304",
    termNumber: 5,
    credits: 6,
    isGeneral: true,
  },
  {
    name: "Análisis Estructural II",
    code: "IG504",
    termNumber: 6,
    credits: 3,
    isGeneral: true,
  },
  {
    name: "Relaciones de Trabajo en la Empresa",
    code: "AD314",
    termNumber: 6,
    credits: 3,
    isGeneral: true,
  },
  {
    name: "Microeconomía",
    code: "CE201",
    termNumber: 6,
    credits: 3,
    isGeneral: true,
  },
  {
    name: "Administración Financiera II",
    code: "FZ401",
    termNumber: 6,
    credits: 3,
    isGeneral: true,
  },
  {
    name: "Inmunología",
    code: "MD406",
    termNumber: 6,
    credits: 4,
    isGeneral: true,
  },
  {
    name: "Macroeconomía",
    code: "CE304",
    termNumber: 7,
    credits: 3,
    isGeneral: true,
  },
  { name: "Ventas", code: "MC402", termNumber: 7, credits: 3, isGeneral: true },
  {
    name: "Comportamiento Humano y Desarrollo Organizacional",
    code: "AD403",
    termNumber: 7,
    credits: 3,
    isGeneral: true,
  },
  {
    name: "Publicidad I",
    code: "MC410",
    termNumber: 7,
    credits: 3,
    isGeneral: true,
  },
  {
    name: "Investigación de Operaciones Aplicada a la Administración",
    code: "PR408",
    termNumber: 7,
    credits: 3,
    isGeneral: true,
  },
  {
    name: "Microbiología",
    code: "BG404",
    termNumber: 7,
    credits: 7,
    isGeneral: true,
  },
  {
    name: "Epidemiología",
    code: "MD306",
    termNumber: 7,
    credits: 4,
    isGeneral: true,
  },
  {
    name: "Planeación Estratégica",
    code: "AD532",
    termNumber: 9,
    credits: 3,
    isGeneral: true,
  },
  {
    name: "Comercio Internacional",
    code: "MC412",
    termNumber: 9,
    credits: 3,
    isGeneral: true,
  },
  {
    name: "Mercadotecnia Social",
    code: "MC506",
    termNumber: 9,
    credits: 3,
    isGeneral: true,
  },
  {
    name: "Formulación y Evaluación de Proyectos",
    code: "AD401",
    termNumber: 11,
    credits: 3,
    isGeneral: true,
  },
  {
    name: "Negocios Electrónicos",
    code: "MC512",
    termNumber: 11,
    credits: 3,
    isGeneral: true,
  },
  {
    name: "Mercadotecnia Internacional",
    code: "MC511",
    termNumber: 11,
    credits: 3,
    isGeneral: true,
  },
  {
    name: "Práctica Profesional Supervisada",
    code: "IF400",
    termNumber: 13,
    credits: 0,
    isGeneral: true,
  },
  {
    name: "Servicio Social",
    code: "MD900",
    termNumber: 20,
    credits: 0,
    isGeneral: true,
  },
];

const SUBJECTS_BY_UNIT = {
  ARQ: [
    { name: "Introduccion al diseño", code: "ARQ101", termNumber: 2, credits: 4 },
    {
      name: "Teoria de la Arquitectura I",
      code: "ARQ201",
      termNumber: 3,
      credits: 3,
    },
    { name: "Diseño Basico I", code: "ARQ301", termNumber: 3, credits: 4 },
    { name: "Expresion Grafica I", code: "ARQ401", termNumber: 3, credits: 4 },
    { name: "Geometria Descriptiva I", code: "GEO101", termNumber: 3, credits: 4 },
    {
      name: "Teoria de la Arquitectura II",
      code: "ARQ202",
      termNumber: 4,
      credits: 3,
    },
    { name: "Diseño Basico II", code: "ARQ302", termNumber: 4, credits: 4 },
    { name: "Expresion Grafica II", code: "ARQ402", termNumber: 4, credits: 4 },
    {
      name: "Geometria Descriptiva II",
      code: "GEO102",
      termNumber: 4,
      credits: 4,
    },
    { name: "Diseño Basico III", code: "ARQ303", termNumber: 5, credits: 4 },
    {
      name: "Resistencia de Materiales",
      code: "ARQ501",
      termNumber: 6,
      credits: 3,
    },
    {
      name: "Materiales y procedimientos constructivos I",
      code: "ARQ502",
      termNumber: 6,
      credits: 4,
    },
    {
      name: "Dibujo Aplicado a la arquitectura",
      code: "ARQ503",
      termNumber: 6,
      credits: 4,
    },
    {
      name: "Historia de la Arquitectura I",
      code: "ARQ504",
      termNumber: 6,
      credits: 4,
    },
    {
      name: "Materiales y Procedimientos Constructivos II",
      code: "ARQ601",
      termNumber: 7,
      credits: 4,
    },
    { name: "Diseño Intermedio I", code: "ARQ602", termNumber: 7, credits: 4 },
    { name: "Expresion Digital I", code: "ARQ603", termNumber: 7, credits: 4 },
    {
      name: "Historia de la Arquitectura II",
      code: "ARQ604",
      termNumber: 7,
      credits: 4,
    },
    {
      name: "Instalacion de edificios I",
      code: "ARQ701",
      termNumber: 8,
      credits: 3,
    },
    { name: "Diseño Intermedio II", code: "ARQ702", termNumber: 8, credits: 4 },
    { name: "Expresion Digital II", code: "ARQ703", termNumber: 8, credits: 4 },
    {
      name: "Historia de la Arquitectura III",
      code: "ARQ704",
      termNumber: 8,
      credits: 4,
    },
    {
      name: "Instalacion de Edificios II",
      code: "ARQ705",
      termNumber: 8,
      credits: 3,
    },
    {
      name: "Analisis Estructural III",
      code: "ARQ801",
      termNumber: 9,
      credits: 4,
    },
    { name: "Diseño Intermedio III", code: "ARQ802", termNumber: 9, credits: 4 },
    { name: "Taller Constructivo I", code: "ARQ803", termNumber: 9, credits: 4 },
    { name: "Monumentos Religiosos", code: "ARQ804", termNumber: 9, credits: 3 },
    {
      name: "Instalacion de Edificios III",
      code: "ARQ805",
      termNumber: 9,
      credits: 3,
    },
    { name: "Taller Constructivo II", code: "ARQ901", termNumber: 10, credits: 4 },
    {
      name: "Administracion de Obras I",
      code: "ARQ1001",
      termNumber: 11,
      credits: 3,
    },
    {
      name: "Administracion de Obras II",
      code: "ARQ1101",
      termNumber: 12,
      credits: 3,
    },
    { name: "Diseño Avanzado I", code: "ARQ1102", termNumber: 12, credits: 4 },
    { name: "Urbanismo", code: "ARQ1103", termNumber: 12, credits: 5 },
    {
      name: "Administracion de Obras III",
      code: "ARQ1201",
      termNumber: 13,
      credits: 3,
    },
    { name: "Diseño Avanzado II", code: "ARQ1202", termNumber: 13, credits: 4 },
    {
      name: "Urbanismo y Ambiente I",
      code: "ARQ1203",
      termNumber: 13,
      credits: 4,
    },
    { name: "Pasajismo", code: "ARQ1204", termNumber: 13, credits: 4 },
    { name: "Diseño Avanzado III", code: "ARQ1301", termNumber: 14, credits: 3 },
    {
      name: "Urbanismo y ambiente II",
      code: "ARQ1302",
      termNumber: 14,
      credits: 3,
    },
    {
      name: "Arquitectura Bioclimatica",
      code: "ARQ1303",
      termNumber: 14,
      credits: 3,
    },
    {
      name: "Seminario de Diseño Avanzado",
      code: "ARQ1401",
      termNumber: 15,
      credits: 4,
    },
  ],
  COM: [
    { name: "Expresión y Creatividad", code: "COM007", termNumber: 2, credits: 3 },
    {
      name: "Procesos Comunicacionales",
      code: "COM008",
      termNumber: 2,
      credits: 3,
    },
    { name: "Fotografía", code: "COM011", termNumber: 3, credits: 3 },
    { name: "Comunicación Escrita", code: "COM012", termNumber: 3, credits: 3 },
    {
      name: "Comunicación Interpersonal",
      code: "COM013",
      termNumber: 3,
      credits: 3,
    },
    {
      name: "Historia de la Comunicación",
      code: "COM015",
      termNumber: 3,
      credits: 3,
    },
    { name: "Opinión Pública", code: "COM016", termNumber: 4, credits: 3 },
    { name: "Periodismo", code: "COM017", termNumber: 4, credits: 3 },
    { name: "Comunicación Masiva", code: "COM018", termNumber: 4, credits: 3 },
    { name: "Taller de Minimedios", code: "COM019", termNumber: 4, credits: 3 },
    { name: "Teoría de la Imagen", code: "COM020", termNumber: 4, credits: 3 },
    { name: "Radio", code: "COM021", termNumber: 5, credits: 3 },
    { name: "Redacción Periodística", code: "COM022", termNumber: 5, credits: 3 },
    {
      name: "Administración de Medios",
      code: "COM023",
      termNumber: 5,
      credits: 3,
    },
    { name: "Comunicación e Iglesia", code: "COM024", termNumber: 5, credits: 3 },
    {
      name: "Ciencia y Tecnología COM",
      code: "COM025",
      termNumber: 5,
      credits: 3,
    },
    { name: "Televisión", code: "COM026", termNumber: 6, credits: 3 },
    {
      name: "Taller de Entrevista y Reportaje",
      code: "COM027",
      termNumber: 6,
      credits: 3,
    },
    { name: "Planificación de Medios", code: "COM028", termNumber: 6, credits: 3 },
    {
      name: "Legislación en la Comunicación",
      code: "COM030",
      termNumber: 6,
      credits: 3,
    },
    {
      name: "Proyectos de Programas de Televisión",
      code: "COM031",
      termNumber: 7,
      credits: 4,
    },
    {
      name: "Periodismo Especializado",
      code: "COM032",
      termNumber: 7,
      credits: 3,
    },
    { name: "Comunicación y Cultura", code: "COM033", termNumber: 7, credits: 3 },
    { name: "Publicidad y Propaganda", code: "COM034", termNumber: 7, credits: 3 },
    { name: "Estética y Lenguaje", code: "COM035", termNumber: 7, credits: 3 },
    { name: "Taller de Radio", code: "COM036", termNumber: 8, credits: 3 },
    {
      name: "Comunicación y Educación",
      code: "COM037",
      termNumber: 8,
      credits: 3,
    },
    { name: "Relaciones Públicas I", code: "COM038", termNumber: 8, credits: 3 },
    { name: "Marketing Publicitario", code: "COM039", termNumber: 8, credits: 3 },
    {
      name: "Proyectos de Programas de Radio",
      code: "COM041",
      termNumber: 9,
      credits: 3,
    },
    {
      name: "Comunicación Corporativa",
      code: "COM042",
      termNumber: 9,
      credits: 3,
    },
    { name: "Relaciones Públicas II", code: "COM043", termNumber: 9, credits: 3 },
    {
      name: "Producción y Creatividad Publicitaria",
      code: "COM044",
      termNumber: 9,
      credits: 3,
    },
    { name: "Relaciones Humanas", code: "COM046", termNumber: 10, credits: 3 },
    {
      name: "Comunicación y Desarrollo",
      code: "COM047",
      termNumber: 10,
      credits: 3,
    },
    {
      name: "Mercadotecnia Social COM",
      code: "COM048",
      termNumber: 10,
      credits: 3,
    },
    {
      name: "Taller de Redacción Publicitaria",
      code: "COM049",
      termNumber: 10,
      credits: 3,
    },
    {
      name: "Programas Informativos para Radio y Televisión",
      code: "COM051",
      termNumber: 11,
      credits: 3,
    },
    {
      name: "Producción de Mensajes para el Desarrollo",
      code: "COM052",
      termNumber: 11,
      credits: 3,
    },
    { name: "Cine", code: "COM053", termNumber: 11, credits: 3 },
    { name: "Campañas Publicitarias", code: "COM054", termNumber: 11, credits: 3 },
    {
      name: "Comunicación e Integración",
      code: "COM056",
      termNumber: 12,
      credits: 3,
    },
    {
      name: "Diseño y Gestión de la Comunicación",
      code: "COM057",
      termNumber: 12,
      credits: 3,
    },
    { name: "Multimedia", code: "COM058", termNumber: 12, credits: 3 },
    {
      name: "Campañas de Propaganda Política",
      code: "COM059",
      termNumber: 12,
      credits: 3,
    },
  ],
  DEN: [
    { name: "Anatomía General DEN", code: "AN104", termNumber: 4, credits: 7 },
    {
      name: "Educación para la Salud Bucal",
      code: "ED101",
      termNumber: 5,
      credits: 3,
    },
    { name: "Anatomía Cabeza y Cuello", code: "AN105", termNumber: 5, credits: 4 },
    { name: "Neuroanatomía DEN", code: "NR104", termNumber: 5, credits: 6 },
    { name: "Biomateriales Dentales", code: "BM101", termNumber: 6, credits: 3 },
    { name: "Fisiología Odontológica", code: "FS109", termNumber: 6, credits: 4 },
    {
      name: "Histología y Embriología Bucodental",
      code: "HS108",
      termNumber: 6,
      credits: 4,
    },
    { name: "Anatomía Dental", code: "AN106", termNumber: 6, credits: 6 },
    {
      name: "Farmacología Odontológica",
      code: "FR104",
      termNumber: 7,
      credits: 4,
    },
    {
      name: "Patología General Odontológica",
      code: "PT104",
      termNumber: 7,
      credits: 4,
    },
    { name: "Odontología Preventiva I", code: "OD101", termNumber: 7, credits: 4 },
    { name: "Semiología Odontológica", code: "SM104", termNumber: 7, credits: 4 },
    { name: "Radiología", code: "RD102", termNumber: 7, credits: 5 },
    {
      name: "Terapéutica Farmacológica Odontológica",
      code: "TR104",
      termNumber: 8,
      credits: 4,
    },
    { name: "Patología Bucal", code: "PT105", termNumber: 8, credits: 4 },
    {
      name: "Odontología Preventiva II",
      code: "OD102",
      termNumber: 8,
      credits: 4,
    },
    { name: "Medicina Interna DEN", code: "MD110", termNumber: 8, credits: 4 },
    { name: "Oclusión", code: "OC101", termNumber: 8, credits: 5 },
    { name: "Periodoncia I", code: "PR105", termNumber: 9, credits: 6 },
    { name: "Odontopediatría I", code: "OD103", termNumber: 9, credits: 5 },
    { name: "Operatoria Dental I", code: "OP101", termNumber: 9, credits: 5 },
    { name: "Endodoncia I", code: "EN114", termNumber: 9, credits: 4 },
    { name: "Prótesis Removible I", code: "PR106", termNumber: 10, credits: 5 },
    { name: "Periodoncia II", code: "PR107", termNumber: 10, credits: 6 },
    { name: "Odontopediatría II", code: "OD104", termNumber: 10, credits: 5 },
    { name: "Operatoria Dental II", code: "OP102", termNumber: 10, credits: 7 },
    { name: "Endodoncia II", code: "EN115", termNumber: 10, credits: 6 },
    { name: "Prótesis Removible II", code: "PR108", termNumber: 11, credits: 6 },
    { name: "Prótesis Fija I", code: "PR109", termNumber: 11, credits: 5 },
    { name: "Ortodoncia", code: "OR102", termNumber: 11, credits: 5 },
    { name: "Cirugía Bucal I", code: "CR104", termNumber: 11, credits: 6 },
    { name: "Prótesis Fija II", code: "PR110", termNumber: 12, credits: 6 },
    { name: "Operatoria Dental III", code: "OP103", termNumber: 12, credits: 9 },
    { name: "Cirugía Bucal II", code: "CR105", termNumber: 12, credits: 6 },
    { name: "Prótesis Total", code: "PR111", termNumber: 13, credits: 6 },
    {
      name: "Técnicas Estéticas Odontológicas",
      code: "TC101",
      termNumber: 13,
      credits: 6,
    },
    { name: "Clínica Integrada I", code: "CL101", termNumber: 13, credits: 10 },
    {
      name: "Odontología Forense y Legal",
      code: "OD105",
      termNumber: 13,
      credits: 5,
    },
    { name: "Odontología Geriátrica", code: "OD106", termNumber: 14, credits: 6 },
    {
      name: "Administración en Salud Pública",
      code: "AD103",
      termNumber: 14,
      credits: 3,
    },
    { name: "Clínica Integrada II", code: "CL102", termNumber: 14, credits: 10 },
    { name: "Informática Biomédica", code: "IN115", termNumber: 14, credits: 3 },
  ],
  DER: [
    {
      name: "Introducción al Estudio del Derecho",
      code: "LG101",
      termNumber: 1,
      credits: 3,
    },
    {
      name: "Teoría General del Proceso",
      code: "LG207",
      termNumber: 2,
      credits: 4,
    },
    { name: "Derecho Romano", code: "LG204", termNumber: 2, credits: 4 },
    { name: "Teoría Política", code: "LG212", termNumber: 2, credits: 4 },
    { name: "Derecho Penal I", code: "LG205", termNumber: 3, credits: 4 },
    { name: "Derecho Civil I", code: "LG303", termNumber: 3, credits: 4 },
    { name: "Teoría del Estado", code: "LG308", termNumber: 3, credits: 3 },
    {
      name: "Derecho del Trabajo y Seguridad Social I",
      code: "LG209",
      termNumber: 3,
      credits: 3,
    },
    { name: "Derecho Procesal Civil I", code: "LG306", termNumber: 4, credits: 4 },
    { name: "Derecho Civil II", code: "LG402", termNumber: 4, credits: 4 },
    { name: "Derecho Penal II", code: "LG305", termNumber: 4, credits: 4 },
    {
      name: "Derecho del Trabajo y Seguridad Social II",
      code: "LG310",
      termNumber: 4,
      credits: 3,
    },
    { name: "Derecho Constitucional", code: "LG318", termNumber: 4, credits: 4 },
    {
      name: "Derecho Procesal Civil II",
      code: "LG317",
      termNumber: 5,
      credits: 4,
    },
    { name: "Derecho Civil III", code: "LG304", termNumber: 5, credits: 4 },
    {
      name: "Derecho de la Niñez y la Mujer",
      code: "LG414",
      termNumber: 5,
      credits: 3,
    },
    { name: "Derecho Administrativo I", code: "LG314", termNumber: 5, credits: 4 },
    {
      name: "Lógica y Argumentación Jurídica",
      code: "LG348",
      termNumber: 7,
      credits: 3,
    },
    { name: "Derecho Civil V", code: "LG309", termNumber: 7, credits: 4 },
    { name: "Derecho Tributario", code: "LG334", termNumber: 7, credits: 3 },
    {
      name: "Derecho Administrativo II",
      code: "LG324",
      termNumber: 7,
      credits: 4,
    },
    {
      name: "Legislación Penal Especial",
      code: "LG325",
      termNumber: 8,
      credits: 3,
    },
    {
      name: "Derecho Internacional Público",
      code: "LG410",
      termNumber: 8,
      credits: 3,
    },
    { name: "Derecho Mercantil I", code: "LG404", termNumber: 8, credits: 3 },
    {
      name: "Redacción y Oratoria Forense",
      code: "LG206",
      termNumber: 8,
      credits: 3,
    },
    { name: "Derechos Humanos", code: "LG510", termNumber: 8, credits: 3 },
    { name: "Derecho Agrario", code: "LG211", termNumber: 9, credits: 3 },
    { name: "Derecho Notarial", code: "LG358", termNumber: 9, credits: 4 },
    { name: "Derecho Mercantil II", code: "LG501", termNumber: 9, credits: 3 },
    {
      name: "Derecho de la Propiedad Intelectual y Comunicaciones",
      code: "LG356",
      termNumber: 9,
      credits: 3,
    },
    { name: "Derecho Ambiental", code: "LG320", termNumber: 9, credits: 3 },
    { name: "Derecho de Integración", code: "LG508", termNumber: 10, credits: 3 },
    {
      name: "Derecho Internacional Privado",
      code: "LG355",
      termNumber: 10,
      credits: 3,
    },
    { name: "Práctica Forense Civil", code: "LG396", termNumber: 10, credits: 3 },
    { name: "Práctica Forense Penal", code: "LG397", termNumber: 10, credits: 3 },
    {
      name: "Práctica Forense Laboral",
      code: "LG398",
      termNumber: 10,
      credits: 3,
    },
    {
      name: "Métodos y Técnicas de Investigación Jurídica",
      code: "LG240",
      termNumber: 11,
      credits: 3,
    },
    {
      name: "Derecho Mercantil Especial",
      code: "LG369",
      termNumber: 11,
      credits: 3,
    },
    { name: "Filosofía del Derecho", code: "LG213", termNumber: 11, credits: 3 },
    { name: "Derecho Comparado", code: "LG316", termNumber: 12, credits: 3 },
    {
      name: "Métodos Alternos de Solución de Controversias",
      code: "LG399",
      termNumber: 12,
      credits: 3,
    },
    { name: "Derecho Canónico", code: "LG270", termNumber: 12, credits: 3 },
    { name: "Ética Jurídica", code: "LG241", termNumber: 12, credits: 3 },
    {
      name: "Ciclo de Clínicas Procesales",
      code: "LG999",
      termNumber: 13,
      credits: 8,
    },
  ],
  ENF: [
    {
      name: "Fundamentos de Enfermería",
      code: "FN101",
      termNumber: 2,
      credits: 4,
    },
    {
      name: "Histología para Enfermería",
      code: "HS105",
      termNumber: 3,
      credits: 4,
    },
    {
      name: "Introducción a la Salud Pública y Atención Primaria de la Salud",
      code: "IN107",
      termNumber: 3,
      credits: 4,
    },
    {
      name: "Embriología para Enfermería",
      code: "EM102",
      termNumber: 4,
      credits: 4,
    },
    {
      name: "Prevención en Salud para Enfermería",
      code: "PR103",
      termNumber: 4,
      credits: 4,
    },
    {
      name: "Teorías y Modelos en Enfermería",
      code: "TR103",
      termNumber: 4,
      credits: 4,
    },
    { name: "Anatomía General ENF", code: "AN103", termNumber: 5, credits: 7 },
    {
      name: "Microbiología para Enfermería",
      code: "MC102",
      termNumber: 5,
      credits: 3,
    },
    {
      name: "Parasitología para Enfermería",
      code: "PR104",
      termNumber: 5,
      credits: 3,
    },
    {
      name: "Fisiología para Enfermería",
      code: "FS106",
      termNumber: 5,
      credits: 4,
    },
    { name: "Nutrición y Dietética", code: "NT101", termNumber: 6, credits: 3 },
    {
      name: "Fisiopatología para Enfermería",
      code: "FS107",
      termNumber: 6,
      credits: 4,
    },
    {
      name: "Semiología para Enfermería",
      code: "SM103",
      termNumber: 6,
      credits: 7,
    },
    {
      name: "Psicología Aplicada a la Enfermería",
      code: "PS105",
      termNumber: 6,
      credits: 3,
    },
    {
      name: "Farmacología para Enfermería",
      code: "FR103",
      termNumber: 7,
      credits: 4,
    },
    {
      name: "Enfermería en Cuidados del Adulto",
      code: "EN101",
      termNumber: 7,
      credits: 3,
    },
    {
      name: "Enfermería en Cuidados Materno Infantil",
      code: "EN102",
      termNumber: 7,
      credits: 3,
    },
    {
      name: "Enfermería Basada en Evidencia",
      code: "EN103",
      termNumber: 8,
      credits: 3,
    },
    {
      name: "Enfermería en Cuidados Gineco-Obstétricos",
      code: "EN104",
      termNumber: 8,
      credits: 4,
    },
    { name: "Enfermería Comunitaria", code: "EN105", termNumber: 8, credits: 3 },
    {
      name: "Administración de Servicios de Salud en Enfermería",
      code: "AD102",
      termNumber: 8,
      credits: 3,
    },
    {
      name: "Investigación en Ciencias de la Salud",
      code: "IN108",
      termNumber: 9,
      credits: 3,
    },
    {
      name: "Enfermería en Cuidados del Niño y del Adolescente",
      code: "EN106",
      termNumber: 9,
      credits: 4,
    },
    {
      name: "Enfermería Médico Quirúrgica I",
      code: "EN107",
      termNumber: 9,
      credits: 4,
    },
    {
      name: "Salud Mental y Psicopatología",
      code: "SL101",
      termNumber: 9,
      credits: 5,
    },
    {
      name: "Gestión y Administración Hospitalaria",
      code: "GS103",
      termNumber: 9,
      credits: 3,
    },
    {
      name: "Enfermería Médico Quirúrgica II",
      code: "EN108",
      termNumber: 10,
      credits: 3,
    },
    { name: "Enfermería Ambulatoria", code: "EN109", termNumber: 10, credits: 3 },
    {
      name: "Diseño y Gestión de Proyectos en Salud",
      code: "DS101",
      termNumber: 11,
      credits: 3,
    },
    {
      name: "Enfermería en Rehabilitación y Salud Ocupacional",
      code: "EN110",
      termNumber: 11,
      credits: 3,
    },
    { name: "Enfermería Geriátrica", code: "EN111", termNumber: 11, credits: 3 },
    {
      name: "Enfermería en Emergencia y Cuidados Críticos",
      code: "EN112",
      termNumber: 11,
      credits: 3,
    },
    {
      name: "Enfermería en Cuidados Paliativos",
      code: "EN113",
      termNumber: 11,
      credits: 3,
    },
    {
      name: "Internado Rotatorio en Enfermería Clínica (Ginecología y Obstetricia)",
      code: "IN109",
      termNumber: 12,
      credits: 5,
    },
    {
      name: "Internado Rotatorio en Enfermería Clínica (Pediatría)",
      code: "IN110",
      termNumber: 12,
      credits: 5,
    },
    {
      name: "Internado Rotatorio en Enfermería Clínica (Medicina Interna)",
      code: "IN111",
      termNumber: 12,
      credits: 5,
    },
    {
      name: "Internado Rotatorio en Enfermería Comunitaria",
      code: "IN112",
      termNumber: 13,
      credits: 4,
    },
    {
      name: "Internado Rotatorio en Enfermería Clínica (Cirugía)",
      code: "IN113",
      termNumber: 13,
      credits: 5,
    },
  ],
  GEE: [
    {
      name: "Contabilidad Administrativa I GEE",
      code: "GEE017",
      termNumber: 4,
      credits: 3,
    },
    { name: "Psicología Empresarial", code: "GEE020", termNumber: 4, credits: 3 },
    {
      name: "Contabilidad Administrativa II",
      code: "GEE022",
      termNumber: 5,
      credits: 3,
    },
    {
      name: "Administración Financiera I GEE",
      code: "GEE023",
      termNumber: 5,
      credits: 3,
    },
    {
      name: "Administración de Recursos Humanos GEE",
      code: "GEE025",
      termNumber: 5,
      credits: 3,
    },
    {
      name: "Investigación de Mercados I GEE",
      code: "GEE026",
      termNumber: 6,
      credits: 3,
    },
    {
      name: "Administración Financiera II GEE",
      code: "GEE028",
      termNumber: 6,
      credits: 3,
    },
    {
      name: "Legislación Empresarial GEE",
      code: "GEE029",
      termNumber: 6,
      credits: 3,
    },
    {
      name: "Relaciones de Trabajo en la Empresa GEE",
      code: "GEE030",
      termNumber: 6,
      credits: 3,
    },
    {
      name: "Investigación de Operaciones Aplicada a la Administración GEE",
      code: "GEE031",
      termNumber: 7,
      credits: 3,
    },
    { name: "Mercados Financieros", code: "GEE034", termNumber: 7, credits: 3 },
    {
      name: "Ingeniería de Métodos I GEE",
      code: "GEE036",
      termNumber: 8,
      credits: 3,
    },
    { name: "Finanzas Públicas", code: "GEE038", termNumber: 8, credits: 3 },
    {
      name: "Negociación Internacional y Desarrollo de Franquicias",
      code: "GEE039",
      termNumber: 8,
      credits: 3,
    },
    {
      name: "Protección y Riesgo Empresarial",
      code: "GEE040",
      termNumber: 8,
      credits: 3,
    },
    {
      name: "Administración de la Producción",
      code: "GEE042",
      termNumber: 9,
      credits: 3,
    },
    {
      name: "Administración de Instituciones Financieras",
      code: "GEE043",
      termNumber: 9,
      credits: 3,
    },
    {
      name: "Comercio Internacional GEE",
      code: "GEE044",
      termNumber: 9,
      credits: 3,
    },
    { name: "Ecología Empresarial", code: "GEE045", termNumber: 9, credits: 3 },
    {
      name: "Gestión Estratégica de Agroindustrias",
      code: "GEE048",
      termNumber: 10,
      credits: 3,
    },
    {
      name: "Gestión Estratégica de Empresas Turísticas",
      code: "GEE050",
      termNumber: 10,
      credits: 3,
    },
    {
      name: "Formulación y Evaluación de Proyectos GEE",
      code: "GEE052",
      termNumber: 11,
      credits: 3,
    },
    {
      name: "Técnicas y Estrategias de Negociación",
      code: "GEE053",
      termNumber: 11,
      credits: 3,
    },
    {
      name: "Negocios Electrónicos GEE",
      code: "GEE054",
      termNumber: 11,
      credits: 3,
    },
    {
      name: "Seminario de Administración",
      code: "GEE056",
      termNumber: 12,
      credits: 3,
    },
    {
      name: "Gerencia Estratégica de Proyectos",
      code: "GEE057",
      termNumber: 12,
      credits: 3,
    },
    {
      name: "Gestión Estratégica de Pequeñas y Medianas Empresas",
      code: "GEE058",
      termNumber: 12,
      credits: 3,
    },
    {
      name: "Gestión Estratégica de Empresas",
      code: "GEE059",
      termNumber: 12,
      credits: 3,
    },
  ],
  ICIV: [
    { name: "Dinamica", code: "ICIV001", termNumber: 3, credits: 3 },
    { name: "Mecanica de solidos I", code: "ICIV002", termNumber: 4, credits: 3 },
    { name: "Mecanica de fluidos", code: "ICIV003", termNumber: 4, credits: 3 },
    { name: "Topografia Aplicada", code: "ICIV004", termNumber: 4, credits: 3 },
    {
      name: "Materiales y procesos de construccion",
      code: "ICIV005",
      termNumber: 5,
      credits: 3,
    },
    { name: "Hidrologia", code: "ICIV006", termNumber: 4, credits: 5 },
    {
      name: "Metodos y maquinaria de construccion",
      code: "ICIV007",
      termNumber: 6,
      credits: 3,
    },
    {
      name: "Ingenieria Hidraulica y de riesgos",
      code: "ICIV008",
      termNumber: 6,
      credits: 4,
    },
    { name: "Mecanica de solidos II", code: "ICIV009", termNumber: 7, credits: 3 },
    {
      name: "Analisis Estructural III ICIV",
      code: "ICIV010",
      termNumber: 7,
      credits: 3,
    },
    { name: "Mecanica de suelos", code: "ICIV011", termNumber: 7, credits: 3 },
    {
      name: "Seminario de Investigacion ICIV",
      code: "ICIV012",
      termNumber: 8,
      credits: 3,
    },
    { name: "Concreto", code: "ICIV013", termNumber: 8, credits: 4 },
    { name: "Geotecnia", code: "ICIV014", termNumber: 8, credits: 3 },
    { name: "Ingenieria Sanitaria", code: "ICIV015", termNumber: 8, credits: 4 },
    { name: "Ingenieria Economia", code: "ICIV016", termNumber: 9, credits: 3 },
    {
      name: "Diseño de estructuras de concreto",
      code: "ICIV017",
      termNumber: 9,
      credits: 4,
    },
    {
      name: "Diseño de cimentaciones",
      code: "ICIV018",
      termNumber: 9,
      credits: 4,
    },
    {
      name: "Diseño de carreteras y caminos",
      code: "ICIV019",
      termNumber: 9,
      credits: 3,
    },
    { name: "Diseño de pavimentos", code: "ICIV020", termNumber: 10, credits: 4 },
    {
      name: "Diseño de estructuras metalicas",
      code: "ICIV021",
      termNumber: 10,
      credits: 3,
    },
    {
      name: "Ingenieria Sanitaria II",
      code: "ICIV022",
      termNumber: 10,
      credits: 3,
    },
    {
      name: "Costos y Presupuesto de obras",
      code: "ICIV023",
      termNumber: 11,
      credits: 4,
    },
    { name: "Obras de Mitigacion", code: "ICIV024", termNumber: 11, credits: 4 },
    {
      name: "Diseño de instalaciones Electricas",
      code: "ICIV025",
      termNumber: 11,
      credits: 3,
    },
    {
      name: "Diseño de obras Civiles asistido por computadora",
      code: "ICIV026",
      termNumber: 11,
      credits: 4,
    },
    {
      name: "Formulacion y Evaluacion de Proyectos de construccion",
      code: "ICIV027",
      termNumber: 12,
      credits: 3,
    },
    { name: "Diseño de puentes", code: "ICIV028", termNumber: 12, credits: 4 },
    {
      name: "Taller de Diseño combinado",
      code: "ICIV029",
      termNumber: 12,
      credits: 4,
    },
    {
      name: "Diseño de Urbanizaciones",
      code: "ICIV030",
      termNumber: 12,
      credits: 4,
    },
  ],
  ICC: [
    {
      name: "Introducción a las Ciencias de la Computación",
      code: "IF112",
      termNumber: 1,
      credits: 4,
    },
    {
      name: "Fundamentos y Lógica de Programación",
      code: "IF200",
      termNumber: 2,
      credits: 4,
    },
    {
      name: "Programación Estructurada I",
      code: "IF214",
      termNumber: 3,
      credits: 3,
    },
    { name: "Estructuras Discretas", code: "IF213", termNumber: 3, credits: 3 },
    {
      name: "Programación Estructurada II",
      code: "IF303",
      termNumber: 4,
      credits: 3,
    },
    { name: "Bases de Datos I", code: "IF322", termNumber: 5, credits: 3 },
    {
      name: "Programación en Entornos de Desarrollo Visual",
      code: "IF325",
      termNumber: 5,
      credits: 3,
    },
    {
      name: "Principios de Electrónica",
      code: "IF319",
      termNumber: 5,
      credits: 3,
    },
    { name: "Bases de Datos II", code: "IF327", termNumber: 6, credits: 3 },
    {
      name: "Análisis y Diseño de Sistemas",
      code: "IF212",
      termNumber: 6,
      credits: 3,
    },
    { name: "Redes I", code: "IF323", termNumber: 6, credits: 4 },
    { name: "Circuitos Lógicos", code: "IF324", termNumber: 6, credits: 3 },
    {
      name: "Bases de Datos Multidimensional",
      code: "IF342",
      termNumber: 7,
      credits: 3,
    },
    {
      name: "Programación Multiplataforma",
      code: "IF340",
      termNumber: 7,
      credits: 3,
    },
    { name: "Desarrollo de Software", code: "IF314", termNumber: 7, credits: 4 },
    { name: "Redes II", code: "IF328", termNumber: 7, credits: 4 },
    {
      name: "Sistemas Automatizados ICC",
      code: "IF329",
      termNumber: 7,
      credits: 3,
    },
    {
      name: "Sistemas Inteligentes para Negocios",
      code: "IF391",
      termNumber: 8,
      credits: 3,
    },
    {
      name: "Implementación de Sistemas de Software",
      code: "IF346",
      termNumber: 8,
      credits: 3,
    },
    { name: "Sistemas Operativos I", code: "IF345", termNumber: 8, credits: 3 },
    { name: "Microcontroladores", code: "IF370", termNumber: 8, credits: 3 },
    {
      name: "Desarrollo de Portales Web I",
      code: "IF353",
      termNumber: 9,
      credits: 3,
    },
    { name: "Programación Movil I", code: "IF351", termNumber: 9, credits: 3 },
    { name: "Sistemas Operativos II", code: "IF352", termNumber: 9, credits: 3 },
    {
      name: "Seminario de Hardware y Electricidad",
      code: "IF381",
      termNumber: 9,
      credits: 3,
    },
    {
      name: "Desarrollo de Portales Web II",
      code: "IF357",
      termNumber: 10,
      credits: 3,
    },
    { name: "Programación Movil II", code: "IF355", termNumber: 10, credits: 3 },
    {
      name: "Gestión y Estandares de Tecnología de Información",
      code: "IF356",
      termNumber: 10,
      credits: 3,
    },
    { name: "Negocios Web", code: "IF362", termNumber: 11, credits: 3 },
    {
      name: "Programación de Negocios",
      code: "IF347",
      termNumber: 11,
      credits: 3,
    },
    {
      name: "Seguridad Informática y Gestión de Riesgo",
      code: "IF360",
      termNumber: 11,
      credits: 3,
    },
    {
      name: "Administración de Centros de Computo",
      code: "IF358",
      termNumber: 11,
      credits: 3,
    },
    {
      name: "SeminarioTaller de Software",
      code: "IF361",
      termNumber: 12,
      credits: 3,
    },
    {
      name: "Gestión de Proyectos Informáticos",
      code: "IF392",
      termNumber: 12,
      credits: 3,
    },
    { name: "Big Data", code: "IF350", termNumber: 12, credits: 3 },
    {
      name: "Auditoría de Sistemas de Información",
      code: "IF380",
      termNumber: 12,
      credits: 3,
    },
  ],
  IIND: [
    {
      name: "Diseño industrial asistido por computadora",
      code: "IIND001",
      termNumber: 4,
      credits: 3,
    },
    {
      name: "Metodos y tecnicas de investigacion IIND",
      code: "IIND002",
      termNumber: 4,
      credits: 3,
    },
    {
      name: "Investigacion de Operaciones I",
      code: "IIND003",
      termNumber: 5,
      credits: 4,
    },
    {
      name: "Ecuaciones Diferenciales IIND",
      code: "IIND004",
      termNumber: 5,
      credits: 3,
    },
    {
      name: "Investigacion de Operaciones II",
      code: "IIND005",
      termNumber: 6,
      credits: 3,
    },
    {
      name: "Ingenieria de métodos I",
      code: "IIND006",
      termNumber: 6,
      credits: 3,
    },
    {
      name: "Produccion limpia y energías Alternativas",
      code: "IIND007",
      termNumber: 6,
      credits: 3,
    },
    {
      name: "Contabilidad de costos para ing. Industrial",
      code: "IIND008",
      termNumber: 6,
      credits: 3,
    },
    {
      name: "Administracion de la produccion y operaciones",
      code: "IIND009",
      termNumber: 7,
      credits: 3,
    },
    {
      name: "Ingenieria de métodos II",
      code: "IIND010",
      termNumber: 7,
      credits: 3,
    },
    {
      name: "Instalaciones electricas IIND",
      code: "IIND011",
      termNumber: 7,
      credits: 3,
    },
    {
      name: "Mecanica de solidos I IIND",
      code: "IIND012",
      termNumber: 7,
      credits: 4,
    },
    { name: "Ergonomia", code: "IIND013", termNumber: 8, credits: 3 },
    {
      name: "Algoritmos y lenguajes de programacion",
      code: "IIND014",
      termNumber: 8,
      credits: 3,
    },
    {
      name: "Gestion de Recursos Humanos",
      code: "IIND015",
      termNumber: 8,
      credits: 3,
    },
    {
      name: "Ciencias de los materiales",
      code: "IIND016",
      termNumber: 8,
      credits: 3,
    },
    { name: "Simulacion de procesos", code: "IIND017", termNumber: 9, credits: 3 },
    {
      name: "Diseño de planta y manejo de materiales",
      code: "IIND018",
      termNumber: 9,
      credits: 3,
    },
    {
      name: "Mecanica de fluidos aplicada",
      code: "IIND019",
      termNumber: 9,
      credits: 3,
    },
    {
      name: "Administracion financiera IIND",
      code: "IIND020",
      termNumber: 9,
      credits: 3,
    },
    {
      name: "Logistica y cadena de suministro",
      code: "IIND021",
      termNumber: 10,
      credits: 3,
    },
    {
      name: "Ingenieria en sistemas de producción I",
      code: "IIND022",
      termNumber: 10,
      credits: 3,
    },
    {
      name: "Ingenieria Economica IIND",
      code: "IIND023",
      termNumber: 10,
      credits: 3,
    },
    {
      name: "Formulacion y Evaluacion de proyectos IIND",
      code: "IIND024",
      termNumber: 11,
      credits: 3,
    },
    {
      name: "Ingenieria en sistemas de producción II",
      code: "IIND025",
      termNumber: 11,
      credits: 3,
    },
    {
      name: "Sistemas Automatizados IIND",
      code: "IIND026",
      termNumber: 11,
      credits: 4,
    },
    {
      name: "Legislacion Empresarial IIND",
      code: "IIND027",
      termNumber: 11,
      credits: 3,
    },
    {
      name: "Analisis y Estrategia de la industria",
      code: "IIND028",
      termNumber: 12,
      credits: 3,
    },
    {
      name: "Ingenieria en sistemas de mantenimiento industrial",
      code: "IIND029",
      termNumber: 12,
      credits: 4,
    },
    {
      name: "Seguridad e higiene en el trabajo",
      code: "IIND030",
      termNumber: 12,
      credits: 3,
    },
    {
      name: "Aplicacion de sistemas integrados de calidad",
      code: "IIND031",
      termNumber: 12,
      credits: 3,
    },
  ],
  MED: [
    { name: "Historia de la Medicina", code: "HS102", termNumber: 3, credits: 3 },
    { name: "Genética", code: "GN101", termNumber: 4, credits: 5 },
    { name: "Psicología Médica MED", code: "PS101", termNumber: 4, credits: 3 },
    {
      name: "Gestión de la Calidad Total MED",
      code: "GS101",
      termNumber: 5,
      credits: 3,
    },
    { name: "Histología MED", code: "HS103", termNumber: 5, credits: 6 },
    { name: "Anatomía I", code: "AN101", termNumber: 5, credits: 7 },
    { name: "Neuroanatomía I", code: "NR101", termNumber: 5, credits: 6 },
    { name: "Anatomía II", code: "AN102", termNumber: 6, credits: 7 },
    { name: "Inmunología MED", code: "IN101", termNumber: 6, credits: 4 },
    { name: "Neuroanatomía II", code: "NR102", termNumber: 6, credits: 6 },
    {
      name: "Introducción a la Salud Pública",
      code: "IN102",
      termNumber: 6,
      credits: 5,
    },
    { name: "Fisiología I", code: "FS102", termNumber: 7, credits: 6 },
    { name: "Parasitología Médica", code: "PR101", termNumber: 7, credits: 4 },
    { name: "Epidemiología MED", code: "EP101", termNumber: 7, credits: 4 },
    {
      name: "Medicina Basada en Evidencia",
      code: "MD101",
      termNumber: 8,
      credits: 3,
    },
    { name: "Fisiología II", code: "FS103", termNumber: 8, credits: 6 },
    { name: "Psicopatología MED", code: "PS102", termNumber: 8, credits: 5 },
    { name: "Fisiopatología I", code: "FS104", termNumber: 9, credits: 5 },
    { name: "Farmacología I", code: "FR101", termNumber: 9, credits: 5 },
    { name: "Patología General", code: "PT101", termNumber: 9, credits: 8 },
    { name: "Bioética", code: "BT101", termNumber: 9, credits: 3 },
    { name: "Prevención en Salud", code: "PR102", termNumber: 9, credits: 6 },
    { name: "Fisiopatología II", code: "FS105", termNumber: 10, credits: 5 },
    { name: "Farmacología II", code: "FR102", termNumber: 10, credits: 5 },
    { name: "Patología Sistémica", code: "PT102", termNumber: 10, credits: 8 },
    {
      name: "Administración de Servicios de Salud",
      code: "AD105",
      termNumber: 10,
      credits: 3,
    },
    {
      name: "Radiología e Imagenología",
      code: "RD101",
      termNumber: 11,
      credits: 3,
    },
    { name: "Semiología I", code: "SM101", termNumber: 11, credits: 12 },
    { name: "Patología Clínica", code: "PT103", termNumber: 11, credits: 8 },
    {
      name: "Medicina Legal y Patología Forense",
      code: "MD102",
      termNumber: 11,
      credits: 3,
    },
    {
      name: "Terapéutica Farmacológica",
      code: "TR101",
      termNumber: 12,
      credits: 6,
    },
    { name: "Semiología II", code: "SM102", termNumber: 12, credits: 12 },
    { name: "Rehabilitación Física", code: "RH101", termNumber: 12, credits: 3 },
    { name: "Psiquiatría", code: "PS103", termNumber: 12, credits: 5 },
    { name: "Terapéutica Alternativa", code: "TR102", termNumber: 13, credits: 4 },
    {
      name: "Ginecología y Obstetricia I",
      code: "GN102",
      termNumber: 13,
      credits: 8,
    },
    { name: "Medicina Pediátrica I", code: "MD103", termNumber: 13, credits: 8 },
    { name: "Medicina del Adulto I", code: "MD104", termNumber: 13, credits: 8 },
    { name: "Cirugía I", code: "CR101", termNumber: 14, credits: 8 },
    {
      name: "Ginecología y Obstetricia II",
      code: "GN103",
      termNumber: 14,
      credits: 8,
    },
    { name: "Medicina del Adulto II", code: "MD105", termNumber: 14, credits: 8 },
    { name: "Cirugía II", code: "CR102", termNumber: 15, credits: 8 },
    {
      name: "Ginecología y Obstetricia III",
      code: "GN104",
      termNumber: 15,
      credits: 8,
    },
    { name: "Medicina Pediátrica II", code: "MD106", termNumber: 15, credits: 8 },
    { name: "Cirugía III", code: "CR103", termNumber: 16, credits: 5 },
    { name: "Medicina Pediátrica III", code: "MD107", termNumber: 16, credits: 8 },
    { name: "Medicina del Adulto III", code: "MD108", termNumber: 16, credits: 8 },
    { name: "Servicio Comunitario", code: "SR101", termNumber: 16, credits: 12 },
    { name: "Otorrinolaringología", code: "OT101", termNumber: 17, credits: 3 },
    {
      name: "Ortopedia y Traumatología",
      code: "OR101",
      termNumber: 17,
      credits: 4,
    },
    { name: "Urología", code: "UR101", termNumber: 17, credits: 3 },
    { name: "Oftalmología", code: "OF101", termNumber: 17, credits: 3 },
    { name: "Geriatría", code: "GR101", termNumber: 18, credits: 3 },
    { name: "Medicina Fetal", code: "MD109", termNumber: 18, credits: 3 },
    { name: "Neonatología", code: "NN101", termNumber: 18, credits: 3 },
    { name: "Dermatología", code: "DR101", termNumber: 18, credits: 4 },
    { name: "Neurología", code: "NR103", termNumber: 18, credits: 4 },
    { name: "Internado de Cirugía", code: "IN103", termNumber: 19, credits: 12 },
    {
      name: "Internado de Gineco-Obstetricia",
      code: "IN104",
      termNumber: 19,
      credits: 12,
    },
    { name: "Internado de Pediatría", code: "IN105", termNumber: 19, credits: 12 },
    {
      name: "Internado de Medicina Interna",
      code: "IN106",
      termNumber: 19,
      credits: 12,
    },
  ],
  MKT: [
    { name: "Mercadotecnia II", code: "MKT025", termNumber: 5, credits: 3 },
    {
      name: "Matemática Financiera MKT",
      code: "MKT027",
      termNumber: 6,
      credits: 3,
    },
    {
      name: "Investigación de Mercados II",
      code: "MKT028",
      termNumber: 6,
      credits: 3,
    },
    {
      name: "Comportamiento del Consumidor",
      code: "MKT030",
      termNumber: 6,
      credits: 3,
    },
    {
      name: "Investigación de Operaciones Aplicada a la Administración MKT",
      code: "MKT036",
      termNumber: 8,
      credits: 3,
    },
    {
      name: "Administración Financiera II MKT",
      code: "MKT037",
      termNumber: 8,
      credits: 3,
    },
    { name: "Promoción de Ventas", code: "MKT038", termNumber: 8, credits: 3 },
    {
      name: "Políticas de Mercadotecnia",
      code: "MKT039",
      termNumber: 8,
      credits: 3,
    },
    { name: "Publicidad II", code: "MKT040", termNumber: 8, credits: 3 },
    { name: "Análisis de Precios", code: "MKT041", termNumber: 9, credits: 3 },
    {
      name: "Mercadotecnia Social MKT",
      code: "MKT043",
      termNumber: 9,
      credits: 3,
    },
    {
      name: "Mercadotecnia de Servicios",
      code: "MKT044",
      termNumber: 9,
      credits: 3,
    },
    {
      name: "Negocios Int. y Desarrollo de Franquicias",
      code: "MKT045",
      termNumber: 9,
      credits: 3,
    },
    {
      name: "Gestión de la Calidad Total MKT",
      code: "MKT046",
      termNumber: 10,
      credits: 3,
    },
    {
      name: "Distribución y Logística",
      code: "MKT047",
      termNumber: 10,
      credits: 3,
    },
    {
      name: "Mercadotecnia Turística",
      code: "MKT048",
      termNumber: 10,
      credits: 3,
    },
    {
      name: "Mercadotecnia para Instituciones Financieras",
      code: "MKT049",
      termNumber: 10,
      credits: 3,
    },
    {
      name: "Comercio Internacional MKT",
      code: "MKT050",
      termNumber: 10,
      credits: 3,
    },
    {
      name: "Desarrollo de Productos",
      code: "MKT052",
      termNumber: 11,
      credits: 3,
    },
    { name: "Diseño Publicitario", code: "MKT053", termNumber: 11, credits: 3 },
    {
      name: "Mercadotecnia Internacional MKT",
      code: "MKT055",
      termNumber: 11,
      credits: 3,
    },
    {
      name: "Formulación y Evaluación de Proyectos MKT",
      code: "MKT057",
      termNumber: 12,
      credits: 3,
    },
    {
      name: "Seminario de Mercadotecnia",
      code: "MKT058",
      termNumber: 12,
      credits: 3,
    },
    {
      name: "Negocios Electrónicos MKT",
      code: "MKT059",
      termNumber: 12,
      credits: 3,
    },
  ],
  PSI: [
    {
      name: "Introducción a la Psicología",
      code: "PS201",
      termNumber: 1,
      credits: 3,
    },
    {
      name: "Teorías de la Personalidad",
      code: "PS202",
      termNumber: 2,
      credits: 3,
    },
    { name: "Entrevista Psicológica", code: "PS212", termNumber: 3, credits: 3 },
    { name: "Psicofisiología I", code: "PS203", termNumber: 3, credits: 4 },
    { name: "Redacción Psicológica", code: "PS218", termNumber: 4, credits: 3 },
    { name: "Psicofisiología II", code: "PS301", termNumber: 4, credits: 4 },
    {
      name: "Psicología del Desarrollo del Niño",
      code: "PS230",
      termNumber: 4,
      credits: 3,
    },
    { name: "Ética en Psicología", code: "PS214", termNumber: 4, credits: 3 },
    {
      name: "Métodos y Técnicas de Investigación Psicológica",
      code: "PS308",
      termNumber: 5,
      credits: 4,
    },
    {
      name: "Psicología del Desarrollo del Adolescente",
      code: "PS240",
      termNumber: 5,
      credits: 3,
    },
    { name: "Psicometría I", code: "PS325", termNumber: 5, credits: 3 },
    {
      name: "Teoría y Clínica de Psicoanálisis",
      code: "PS260",
      termNumber: 5,
      credits: 4,
    },
    {
      name: "Psicología de las Organizaciones I",
      code: "PS315",
      termNumber: 6,
      credits: 5,
    },
    { name: "Psicología Social I", code: "PS258", termNumber: 6, credits: 3 },
    { name: "Psicometría II", code: "PS335", termNumber: 6, credits: 4 },
    {
      name: "Psicología del Desarrollo de la Adultez y la Vejez",
      code: "PS250",
      termNumber: 6,
      credits: 3,
    },
    { name: "Psicopatología I", code: "PS338", termNumber: 6, credits: 4 },
    {
      name: "Teoría e Intervención en Psicología Humanística",
      code: "PS270",
      termNumber: 7,
      credits: 4,
    },
    { name: "Psicología Social II", code: "PS305", termNumber: 7, credits: 3 },
    { name: "Psicometría III", code: "PS345", termNumber: 7, credits: 4 },
    {
      name: "Psicología del Aprendizaje",
      code: "PS321",
      termNumber: 7,
      credits: 4,
    },
    { name: "Psicopatología II", code: "PS348", termNumber: 7, credits: 4 },
    {
      name: "Teoría e Intervención en Psicología Cognitiva",
      code: "PS280",
      termNumber: 8,
      credits: 4,
    },
    {
      name: "Psicología Preventiva y Salud Pública",
      code: "PS370",
      termNumber: 8,
      credits: 4,
    },
    { name: "Psicología Educativa", code: "PS351", termNumber: 8, credits: 4 },
    { name: "Psicometría IV", code: "PS355", termNumber: 8, credits: 3 },
    { name: "Técnicas Proyectivas I", code: "PS354", termNumber: 8, credits: 4 },
    { name: "Técnicas Terapéuticas I", code: "PS374", termNumber: 9, credits: 4 },
    {
      name: "Teoría y Abordaje de la Intervención en Crisis",
      code: "PS375",
      termNumber: 9,
      credits: 4,
    },
    {
      name: "Psicología de las Organizaciones II",
      code: "PS317",
      termNumber: 9,
      credits: 5,
    },
    {
      name: "Diagnóstico e Intervención Psicoeducativa",
      code: "PS371",
      termNumber: 9,
      credits: 4,
    },
    { name: "Técnicas Proyectivas II", code: "PS364", termNumber: 9, credits: 4 },
    {
      name: "Técnicas Terapéuticas II",
      code: "PS378",
      termNumber: 10,
      credits: 4,
    },
    {
      name: "Orientación y Consejería Psicológica",
      code: "PS384",
      termNumber: 10,
      credits: 4,
    },
    {
      name: "Psicología del Talento Humano",
      code: "PS329",
      termNumber: 10,
      credits: 4,
    },
    {
      name: "Diagnóstico e Informes Psicológicos",
      code: "PS365",
      termNumber: 10,
      credits: 4,
    },
    {
      name: "Seminario de Investigación en Psicología Aplicada",
      code: "PS395",
      termNumber: 11,
      credits: 4,
    },
    {
      name: "Metodología y Modelos de Intervención Comunitaria",
      code: "PS385",
      termNumber: 11,
      credits: 4,
    },
    {
      name: "Orientación Vocacional y Profesional",
      code: "PS381",
      termNumber: 11,
      credits: 4,
    },
    { name: "Psicología Jurídica", code: "PS392", termNumber: 12, credits: 3 },
    {
      name: "Diseño y Desarrollo de Proyectos de Psicología Aplicada",
      code: "PS398",
      termNumber: 12,
      credits: 4,
    },
    {
      name: "Seminario de Salud Mental en Honduras",
      code: "PS390",
      termNumber: 12,
      credits: 3,
    },
    { name: "Psicología del Deporte", code: "PS386", termNumber: 12, credits: 3 },
  ],
};

async function seedSubjects(institutionId, units) {
  console.log("Seeding subjects...");

  const allSubjects = {};

  const uniqueSubjects = {};
  for (const s of GENERAL_SUBJECTS) uniqueSubjects[s.code] = s;
  for (const subjects of Object.values(SUBJECTS_BY_UNIT)) {
    for (const s of subjects) {
      if (s && !uniqueSubjects[s.code]) uniqueSubjects[s.code] = s;
    }
  }

  for (const s of Object.values(uniqueSubjects)) {
    const subject = await prisma.subject.upsert({
      where: { institutionId_code: { institutionId, code: s.code } },
      update: {},
      create: {
        name: s.name,
        code: s.code,
        termNumber: s.termNumber,
        credits: s.credits,
        isGeneral: s.isGeneral || false,
        institutionId,
      },
    });
    allSubjects[s.code] = subject;
  }

  for (const s of GENERAL_SUBJECTS) {
    for (const unit of Object.values(units)) {
      await prisma.unitSubject
        .upsert({
          where: {
            academicUnitId_subjectId: {
              academicUnitId: unit.id,
              subjectId: allSubjects[s.code].id,
            },
          },
          update: {},
          create: { academicUnitId: unit.id, subjectId: allSubjects[s.code].id },
        })
        .catch(() => {});
    }
  }

  for (const [unitCode, subjects] of Object.entries(SUBJECTS_BY_UNIT)) {
    for (const s of subjects) {
      if (!s) continue; // skip any undefined entries
      await prisma.unitSubject
        .upsert({
          where: {
            academicUnitId_subjectId: {
              academicUnitId: units[unitCode].id,
              subjectId: allSubjects[s.code].id,
            },
          },
          update: {},
          create: {
            academicUnitId: units[unitCode].id,
            subjectId: allSubjects[s.code].id,
          },
        })
        .catch(() => {});
    }
  }

  console.log(`${Object.keys(allSubjects).length} subjects seeded`);
  return allSubjects;
}

module.exports = { seedSubjects, SUBJECTS_BY_UNIT, GENERAL_SUBJECTS };
